Align Misc Items

diff --git a/.github/actions/handle-rate-limits/action.yml b/.github/actions/handle-rate-limits/action.yml
--- a/.github/actions/handle-rate-limits/action.yml
+++ b/.github/actions/handle-rate-limits/action.yml
@@ -2,7 +2,7 @@ name: Rate Limit Handler
 description: Check rate limits and dynamically calculate/apply sleep times.
 inputs:
   token:
-    description: Personal Access Token (PAT) for GitHub API.
+    description: GitHub/Personal Access Token.
     required: true
 runs:
   using: "composite"
@@ -22,13 +22,14 @@ runs:
             -H "Accept: application/vnd.github.v3+json" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/rate_limit)
-          printf "Primary Rate Limit Response:\n%s\n" "$RATE_LIMIT_DATA"
+          printf "Primary Rate Limit Data:\n%s\n" "$RATE_LIMIT_DATA"
+          echo ""
 
           # Validate JSON response
           if ! echo "$RATE_LIMIT_DATA" | jq -e '.' > /dev/null 2>&1; then
             SLEEP_TIME=$BASE_TIME
-            echo "Error: Invalid JSON Response!"
-            echo "       Defaulting sleep time to $SLEEP_TIME seconds."
+            echo "Warn: Invalid JSON Response!"
+            echo "      Defaulting sleep time to $SLEEP_TIME seconds."
             return
           fi
 
@@ -39,24 +40,25 @@ runs:
           WAIT_PERIOD=$(( RESET_TIME - CURRENT_TIME ))
           if (( WAIT_PERIOD < 0 )); then
             SLEEP_TIME=$(( BASE_TIME * 2 ))
-            echo "Error: Invalid Wait Time Esitmate!"
-            echo "       Defaulting sleep time to $SLEEP_TIME seconds."
+            echo "Warn: Invalid Wait Time Esitmate!"
+            echo "      Defaulting sleep time to $SLEEP_TIME seconds."
             return
           fi
 
           if (( REMAINING_CALLS > 99 )); then
             SLEEP_TIME=0
-          elif (( REMAINING_CALLS > 1 )); then
+          elif (( REMAINING_CALLS > 10 )); then
             SLEEP_TIME=$(( WAIT_PERIOD / REMAINING_CALLS ))
           else
             SLEEP_TIME=$(( WAIT_PERIOD + 60 ))
           fi
 
+          echo "Note: Calculated sleep time is $SLEEP_TIME seconds."
           if (( SLEEP_TIME < 0 )); then
-            SLEEP_TIME=0
+            echo "      Calculated sleep time is invalid."
+            echo "      Defaulting sleep time to $SLEEP_TIME seconds."
+            SLEEP_TIME=$BASE_TIME
           fi
-
-          echo "Calculated sleep time is $SLEEP_TIME seconds."
         }
 
         handle_secondary_rate_limit() {
@@ -68,20 +70,20 @@ runs:
               https://api.github.com/rate_limit)
             printf "Secondary Rate Limit Response:\n%s\n" "$RESPONSE"
 
-            RETRY_BASE=$(echo "$RESPONSE" | grep -i '^retry-after:' | awk '{print $2}' | tr -d '\r') || true
+            RETRY_BASE=$(echo "$RESPONSE" | grep -i '^Retry-After:' | awk '{print $2}' | tr -d '\r') || true
             if [[ -z "$RETRY_BASE" ]]; then
               # Default to a small retry interval if 'RETRY_BASE' is not set
               RETRY_AFTER=2
-              echo "'Retry-After' header not detected."
-              echo "Proceed after a token $RETRY_AFTER seconds."
+              echo "Note: 'Retry-After' header not detected."
+              echo "      Proceed after a token $RETRY_AFTER second pause."
               sleep "$RETRY_AFTER"
               break
             fi
 
             if ! [[ "$RETRY_BASE" =~ ^[0-9]+$ ]]; then
               # Ensure RETRY_BASE is numeric and valid
-              echo "Error: Invalid 'Retry-After' header value: '$RETRY_BASE'."
-              echo "       Defaulting to $BASE_TIME seconds."
+              echo "Warn: Invalid 'Retry-After' header value: '$RETRY_BASE'."
+              echo "      Defaulting to $BASE_TIME seconds."
               RETRY_BASE=BASE_TIME
             elif (( RETRY_BASE < BASE_TIME )); then
               echo "Warn: Invalid 'RETRY_BASE' value: '$RETRY_BASE'."
@@ -91,8 +93,8 @@ runs:
 
             SCALE_FACTOR=$(( RETRY_COUNT + 1 ))
             RETRY_AFTER=$(( RETRY_BASE * SCALE_FACTOR * SCALE_FACTOR ))
-            echo "Secondary Rate Limit is Active."
-            echo "Wait $RETRY_AFTER seconds for reset..."
+            echo "Note: Secondary Rate Limit is Active."
+            echo "      Wait $RETRY_AFTER seconds for reset."
             sleep "$RETRY_AFTER"
 
             RETRY_COUNT=$SCALE_FACTOR
@@ -100,6 +102,7 @@ runs:
               break
             fi
           done
+          echo ""
         }
 
         # Check for secondary rate limits
