Address Misc Issues

diff --git a/.github/workflows/issue_helper_change_title.yml b/.github/workflows/issue_helper_change_title.yml
--- a/.github/workflows/issue_helper_change_title.yml
+++ b/.github/workflows/issue_helper_change_title.yml
@@ -4,13 +4,24 @@ on:
   workflow_dispatch:
     inputs:
       item_id:
-        description: 'The Issue ID'
+        description: 'Issue ID'
         type: number
         required: true
       new_title:
-        description: 'The New Issue Title'
+        description: 'New Issue Title'
         type: string
         required: true
+      provenance_known:
+        description: 'User RefindPlus Provenance Known?'
+        type: choice
+        options:
+        - 'YES'
+        - 'NO'
+        default: 'YES'
+      provenance_tag:
+        description: 'Optional Tag if NO Above'
+        type: string
+        default: 'Exhibits Issues'
 
 permissions:
   issues: write
@@ -45,9 +56,18 @@ jobs:
               issue_number: issueNumber
             });
             const isLocked = data.locked ? 'true' : 'false';
+            const isClosed = data.state === 'closed' ? 'true' : 'false';
 
+            // To use in the same job
             const fs = require('fs');
+            fs.appendFileSync(process.env.GITHUB_ENV, `isclosed=${isClosed}\n`);
             fs.appendFileSync(process.env.GITHUB_ENV, `islocked=${isLocked}\n`);
+
+            // To use in other jobs ... For reference
+            // Access with 'needs.<job>.outputs'
+            // Must have 'changetitle_01' as a 'needs:' dependency
+            //core.setOutput('isclosed', isClosed);
+            //core.setOutput('islocked', isLocked);
 
       # Set NodeJS Up - https://github.com/actions/setup-node
       - id: changetitle_02
@@ -56,16 +76,90 @@ jobs:
           # Using range for flexibility
           node-version: '>=20 <22'
 
+      - if: github.event.inputs.provenance_known == 'NO'
+        id: changetitle_03
+        uses: actions-cool/issues-helper@v3
+        with:
+          actions: 'create-comment'
+          token: ${{ steps.app-token.outputs.token }}
+          issue-number: ${{ github.event.inputs.item_id }}
+          body: |
+            The issue appears to have arsen from a modified/customised instance.
+            This item is therefore considered invalid and cannot be looked into.
+
+            > [!IMPORTANT]
+            > Issues found on modified/customised builds must be tested on official files/code.
+            > Should they also appear on these sources, raise your issue based on such sources.
+            > Additionally, debug logging and such should be obtained from the offical sources.
+
+            Thank you.
+
+      # Remove Some Prior Labels if Present
+      - if: github.event.inputs.provenance_known == 'NO'
+        id: changetitle_04
+        uses: actions-cool/issues-helper@v3
+        with:
+          actions: 'remove-labels'
+          token: ${{ steps.app-token.outputs.token }}
+          issue-number: ${{ github.event.inputs.item_id }}
+          labels: 'Triage,Queries,Noted,Incomplete,Tagged,Stale'
+
+      # Add 'Invalid' Label
+      - if: github.event.inputs.provenance_known == 'NO'
+        id: changetitle_05
+        uses: actions-cool/issues-helper@v3
+        with:
+          actions: 'add-labels'
+          token: ${{ steps.app-token.outputs.token }}
+          issue-number: ${{ github.event.inputs.item_id }}
+          labels: 'Invalid'
+
+      # Close Issue if Open
+      - if: ${{ github.event.inputs.provenance_known == 'NO' && env.isclosed == 'false' }}
+        id: changetitle_06
+        uses: actions-cool/issues-helper@v3
+        with:
+          actions: 'close-issue'
+          close-reason: 'completed'
+          token: ${{ steps.app-token.outputs.token }}
+          issue-number: ${{ github.event.inputs.item_id }}
+
+      # Lock Issue if Unlocked
+      - if: ${{ github.event.inputs.provenance_known == 'NO' && env.islocked == 'false' }}
+        id: changetitle_07
+        uses: actions-cool/issues-helper@v3
+        with:
+          actions: 'lock-issue'
+          token: ${{ steps.app-token.outputs.token }}
+          issue-number: ${{ github.event.inputs.item_id }}
+          issue-state: 'closed'
+
       # Update Issue Title - GitHub API
-      - id: changetitle_03
+      - id: changetitle_08
         env:
-          GET_TOKEN: ${{ steps.app-token.outputs.token }}
-          GET_REPO: ${{ github.repository }}
-          GET_ISSUE_ID: ${{ github.event.inputs.item_id }}
-          GET_NEW_TITLE: ${{ github.event.inputs.new_title }}
+          ENV_TOKEN: ${{ steps.app-token.outputs.token }}
+          ENV_REPO: ${{ github.repository }}
+          ENV_ISSUE_ID: ${{ github.event.inputs.item_id }}
+          ENV_OUR_TITLE: ${{ github.event.inputs.new_title }}
+          ENV_PROVENANCE_TAG: ${{ github.event.inputs.provenance_tag }}
+          ENV_PROVENANCE_KNOWN: ${{ github.event.inputs.provenance_known }}
+        shell: bash
         run: |
-          curl -X PATCH \
-            -H "Authorization: token ${GET_TOKEN}" \
+          if [ "${ENV_PROVENANCE_KNOWN}" == 'NO' ]; then
+            NewTitle="${ENV_OUR_TITLE}"
+          else
+            # Use default if ENV_PROVENANCE_TAG is blank
+            TheTag="${ENV_PROVENANCE_TAG:-Exhibits Issues}"
+            TheTag="$(echo "${TheTag}" | xargs)"
+            if [ -z "${TheTag}" ]; then
+              TheTag="Exhibits Issues"
+            fi
+            NewTitle="RefindPlus of Unknown Provenance: ${TheTag}"
+          fi
+
+          echo "Updating issue #${ENV_ISSUE_ID} with title: ${NewTitle}"
+          curl -f -X PATCH \
+            -H "Authorization: token ${ENV_TOKEN}" \
             -H "Accept: application/vnd.github.v3+json" \
-            https://api.github.com/repos/${GET_REPO}/issues/${GET_ISSUE_ID} \
-            -d "{\"title\": \"${GET_NEW_TITLE}\"}"
+            https://api.github.com/repos/${ENV_REPO}/issues/${ENV_ISSUE_ID} \
+            -d "{\"title\": \"${NewTitle}\"}" || { echo "Title Update Failed"; exit 1; }
